baseURL = "https://leonardo.zangrando.com"
disqusShortname = ""
languageCode = "en-uk"
languageName = "En"
paginate = "21"
theme = "persian"
title = "Leonardo Zangrando"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
identifier = "how"
name = "How?"
weight = 7
[[menu.main]]
name = "Working Together"
parent = "how"
url = "working-together"
weight = 8
[[menu.main]]
name = "Programmes"
parent = "how"
url = "plans"
weight = 9
[[menu.main]]
identifier = "achieving"
name = "Achieving"
weight = 4
[[menu.main]]
name = "Impact"
parent = "achieving"
url = "categories/impact/"
weight = 6
[[menu.main]]
name = "Greatness"
parent = "achieving"
url = "categories/greatness/"
weight = 5
[[menu.main]]
name = "You"
url = "you"
weight = 3
[[menu.main]]
name = "About"
url = "about"
weight = 2
[[menu.main]]
name = "Thoughts"
url = "post"
weight = 1
[outputs]
home = ["HTML", "RSS", "json"]
[params]
OGImage = "images/wave-or-ocean-w-logo.jpeg"
author = "Leonardo Zangrando"
contact_form_action = "https://docs.google.com/forms/u/2/d/e/1FAIpQLSf3I55AFqkvHrOrEmQNgrs5eBycJbYAfHlr6Ik5oquS8mHlBA/formResponse"
copyright = "©2022 Leonardo Zangrando"
custom_css = ["css/foo.css"]
description = "Highly successful people can be like powerful waves in the Ocean. But there’s only so much that a wave can grow. What about __becoming the Ocean__ instead?\n\nI work with Leaders who want to leave a mark on the world but they feel they can do just so much. I help them multiply their impact on their own life, their business and sustainability.\n\nI guide them to go beyond their past successes as powerful waves and become powerful like the Ocean. \n\nI help them gain clarity of objectives, discover their unique approach to achieve them and  multiply exponentially their impact. \n\nWith transparency, integrity and out-of-the-box thinking.\n\n[Meet](/about) [you](/you) inside!\n\n[Leonardo Zangrando – _Impact Coach_](/about)\n\n![Leonardo Zangrando](images/hero-image.jpg \"Leonardo Zangrando – Ocean Impact Coach\")"
design_by = "Original Web Design By [Themefisher](https://themefisher.com/) & [Gethugothemes](https://gethugothemes.com/)"
heroImage = "images/wave-or-ocean.jpeg"
heroQuote = "_“You can either see yourself as a wave in the Ocean, or you can see yourself as the Ocean.”_  – Oprah Winfrey"
logo = "images/EOlogo1000noclaim.png"
search = false
[params.cookies]
enable = false
expire_days = 2
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
icon = "ti-youtube"
link = "https://youtube.com/c/LeonardoZangrando"
[[params.social]]
icon = "ti-linkedin"
link = "https://linkedin.com/in/leonardozangrando"
[[params.social]]
icon = "ti-email"
link = "mailto:leonardo@zangrando.com"
