baseURL = "https://leonardo.zangrando.com"
disqusShortname = ""
languageCode = "en-uk"
languageName = "En"
paginate = "5"
theme = "persian"
title = "Ocean Impact"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Achieving"
identifier = "achieving"
weight = 5
[[menu.main]]
name = "Impact"
url = "categories/impact/"
parent = "achieving"
weight = 5
[[menu.main]]
name = "Greatness"
url = "categories/greatness/"
parent = "achieving"
weight = 4
[[menu.main]]
name = "You"
url = "you"
weight = 3
[[menu.main]]
name = "About"
url = "about"
weight = 2
[[menu.main]]
name = "Thoughts"
url = "/"
weight = 1
[outputs]
home = ["HTML", "RSS", "json"]
[params]
author = "Leonardo Zangrando"
contact_form_action = "https://docs.google.com/forms/u/2/d/e/1FAIpQLSf3I55AFqkvHrOrEmQNgrs5eBycJbYAfHlr6Ik5oquS8mHlBA/formResponse"
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
custom_css = ["css/foo.css"]
description = "Coaching Powerful People for Ocean Impact. Working with CEOs, Entrepreneurs, Philanthropists and all Powerful People with a passion for the Ocean to multiply exponentially their Impact on Ocean sustainability"
heroImage = "images/wave-or-ocean.jpeg"
heroQuote = "_“You can either see yourself as a wave in the Ocean, or you can see yourself as the Ocean.”_  – Oprah Winfrey"
logo = "images/logo.png"
search = false
[params.cookies]
enable = false
expire_days = 2
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
