baseURL = "https://sustainability-impact-coach.netlify.app"
disqusShortname = ""
languageCode = "en-uk"
languageName = "En"
paginate = "5"
theme = "persian"
title = "Sustainability Impact Coach"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Greatness"
url = "categories/achieving-greatness/"
weight = 4
[[menu.main]]
name = "You"
url = "you"
weight = 3
[[menu.main]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 7
[[menu.main]]
name = "Contact"
url = "contact"
weight = 6
[[menu.main]]
name = "Impact"
url = "categories/ocean-impact/"
weight = 5
[[menu.main]]
name = "About"
url = "about"
weight = 2
[[menu.main]]
name = "Thoughts"
url = "/"
weight = 1
[outputs]
home = ["HTML", "RSS", "json"]
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
custom_css = ["css/foo.css"]
description = "This is meta description"
logo = "images/logo.png"
search = true
[params.cookies]
enable = true
expire_days = 2
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
